POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2N2Q1NGI5MDJlMjMwODY4NDIzMTM0ZTciLCJpYXQiOjE3NDIwNTQ0NTV9.AHILSIPAsGygouE7_Onz5VMozJWNrem5DhgpKNzAahQ

{
  "title": "Title Example",
  "author": "Author Example",
  "url": "http://exampleUrl.com",
  "likes": 10,
  "userId": "67d54b902e230868423134e7"
}