POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Title Example",
  "author": "Author Example",
  "url": "http://exampleUrl.com",
  "likes": 10,
  "userId": "67d54b902e230868423134e7"
}